// Banc de l'outillage de release. Tests NÉGATIFS d'abord : un contrôle qui ne peut pas
// échouer ne contrôle rien. Chaque emplacement de version est dérivé seul, et le banc
// exige que l'écart soit vu, nommé, et qu'il soit le seul.
//
//   node tools/release/tests/release_tooling.mjs
//
// Aucun réseau. Aucun accès au dépôt réel : tout se joue dans un bac à sable temporaire.

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import {
  lireVersions, incoherences, versionValide, versionDuTag,
  remplaceVersionDansLock, lireVersionDansLock, sources,
} from "../version_coherence.mjs";
import { analyser, comparer } from "../../../bump_version.mjs";

const RACINE = path.resolve(path.dirname(new URL(import.meta.url).pathname), "../../..");
let ok = 0, ko = 0;
const ck = (n, c, d = "") => { c ? ok++ : ko++; console.log(`  ${c ? "✓" : "✗"} ${n}${d ? "  → " + d : ""}`); };
const leve = (f) => { try { f(); return null; } catch (e) { return e.message; } };

// --- bac à sable ---------------------------------------------------------------------
const LOCK_CARGO = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "voisin-avant"
version = "9.9.9"

[[package]]
name = "human-origin"
version = "0.3.1"
dependencies = [
 "serde",
]

[[package]]
name = "voisin-apres"
version = "8.8.8"
`;

function sableNeuf(v = "0.3.1") {
  const d = fs.mkdtempSync(path.join(os.tmpdir(), "ho-release-"));
  fs.mkdirSync(path.join(d, "src-tauri"));
  const j = (p, o) => fs.writeFileSync(path.join(d, p), JSON.stringify(o, null, 2) + "\n");
  j("package.json", { name: "human-origin", version: v, scripts: {} });
  j("package-lock.json", { name: "human-origin", version: v, lockfileVersion: 3,
                           packages: { "": { name: "human-origin", version: v } } });
  j("src-tauri/tauri.conf.json", { package: { productName: "HumanOrigin", version: v } });
  fs.writeFileSync(path.join(d, "src-tauri/Cargo.toml"),
    `[package]\nname = "human-origin"\nversion = "${v}"\nedition = "2021"\n`);
  fs.writeFileSync(path.join(d, "src-tauri/Cargo.lock"), LOCK_CARGO.replace('version = "0.3.1"', `version = "${v}"`));
  return d;
}

console.log("\n-- analyse des arguments : l'ordre ne décide de rien --");
{
  // LE défaut historique : npm place les arguments de l'utilisateur APRÈS ceux du script.
  ck("drapeaux d'abord, version ensuite", analyser(["--git", "--tag", "--cargo", "0.3.2"]).version === "0.3.2");
  ck("version d'abord, drapeaux ensuite", analyser(["0.3.2", "--git"]).version === "0.3.2");
  ck("drapeaux conservés", analyser(["--git", "--tag", "0.3.2"]).drapeaux.has("--tag"));
}

console.log("\n-- analyse des arguments : refus --");
for (const [cas, argv, motif] of [
  ["aucun argument", [], "version manquante"],
  ["que des drapeaux", ["--git", "--tag", "--cargo"], "version manquante"],
  ["deux versions", ["0.3.2", "0.3.3"], "une seule version"],
  ["drapeau inconnu", ["0.3.2", "--publier"], "drapeau inconnu"],
  ["version non semver", ["0.3"], "semver"],
  ["forme de tag", ["v0.3.2"], "semver"],
  ["texte libre", ["prochaine"], "semver"],
  ["version vide", [""], "semver"],
]) {
  const m = leve(() => analyser(argv));
  ck(`${cas} refusé`, m !== null && m.includes(motif), m ?? "ACCEPTÉ");
}
ck("préversion acceptée", analyser(["0.3.2-rc.1"]).version === "0.3.2-rc.1");

console.log("\n-- comparaison de versions --");
ck("0.3.2 > 0.3.1", comparer("0.3.2", "0.3.1") === 1);
ck("0.3.1 = 0.3.1", comparer("0.3.1", "0.3.1") === 0);
ck("0.3.0 < 0.3.1", comparer("0.3.0", "0.3.1") === -1);
ck("1.0.0 > 0.9.9", comparer("1.0.0", "0.9.9") === 1);
ck("préversion antérieure à sa version", comparer("0.3.2-rc.1", "0.3.2") === -1);

console.log("\n-- version portée par un tag --");
ck("v0.3.2 donne 0.3.2", versionDuTag("v0.3.2") === "0.3.2");
ck("sans v : refusé", versionDuTag("0.3.2") === null);
ck("v0.3 : refusé", versionDuTag("v0.3") === null);
ck("v28 : refusé", versionDuTag("v28") === null);
ck("vide : refusé", versionDuTag("") === null);
ck("préversion admise", versionDuTag("v0.3.2-rc.1") === "0.3.2-rc.1");

console.log("\n-- Cargo.lock : seul le paquet nommé bouge --");
{
  const sortie = remplaceVersionDansLock(LOCK_CARGO, "human-origin", "0.3.2");
  ck("human-origin monté", lireVersionDansLock(sortie, "human-origin") === "0.3.2");
  ck("voisin d'avant intact", lireVersionDansLock(sortie, "voisin-avant") === "9.9.9");
  ck("voisin d'après intact", lireVersionDansLock(sortie, "voisin-apres") === "8.8.8");
  ck("paquet absent : levée", leve(() => remplaceVersionDansLock(LOCK_CARGO, "inexistant", "1.0.0")) !== null);
  const double = LOCK_CARGO + '\n[[package]]\nname = "human-origin"\nversion = "0.0.1"\n';
  const m = leve(() => remplaceVersionDansLock(double, "human-origin", "0.3.2"));
  ck("paquet en double : levée", m !== null && m.includes("double"), m ?? "ACCEPTÉ");
}

console.log("\n-- cohérence : le cas sain --");
{
  const d = sableNeuf("0.3.1");
  ck("six emplacements lus", lireVersions(d).length === 6);
  ck("aucun écart quand tout concorde", incoherences(lireVersions(d)).length === 0);
  ck("tag concordant accepté", incoherences(lireVersions(d), versionDuTag("v0.3.1")).length === 0);
  fs.rmSync(d, { recursive: true, force: true });
}

console.log("\n-- cohérence : CHAQUE emplacement dérivé seul est vu --");
// C'est ici que le contrôle prouve qu'il n'est pas vide : six dérives, six détections.
for (const cible of sources(".").map((s) => s.nom)) {
  const d = sableNeuf("0.3.1");
  const s = sources(d).find((x) => x.nom === cible);
  s.ecrire(s.chemin, "0.0.9");                         // dérive d'un seul emplacement
  const ecarts = incoherences(lireVersions(d), "0.3.1");
  const vus = ecarts.map((e) => e.nom);
  ck(`dérive de « ${cible} » détectée`, vus.includes(cible), vus.join(", ") || "AUCUN ÉCART");
  fs.rmSync(d, { recursive: true, force: true });
}

console.log("\n-- cohérence : autres refus --");
{
  const d = sableNeuf("0.3.1");
  fs.rmSync(path.join(d, "package-lock.json"));
  const ecarts = incoherences(lireVersions(d), "0.3.1");
  ck("fichier absent : écart signalé", ecarts.some((e) => e.nom.startsWith("package-lock")), JSON.stringify(ecarts));
  fs.rmSync(d, { recursive: true, force: true });
}
{
  const d = sableNeuf("0.3.1");
  const s = sources(d).find((x) => x.nom === "package.json");
  s.ecrire(s.chemin, "pas-une-version");
  const ecarts = incoherences(lireVersions(d));        // package.json fait foi : référence invalide
  ck("référence non semver : refus", ecarts.length > 0 && ecarts[0].nom === "référence", JSON.stringify(ecarts));
  fs.rmSync(d, { recursive: true, force: true });
}
ck("tag divergent : écart sur toutes les sources", (() => {
  const d = sableNeuf("0.3.1");
  const n = incoherences(lireVersions(d), "0.3.2").length;
  fs.rmSync(d, { recursive: true, force: true });
  return n === 6;
})());

console.log("\n-- bump de bout en bout, dans le bac à sable --");
{
  const d = sableNeuf("0.3.1");
  const r = execFileSync("node", [path.join(RACINE, "bump_version.mjs"), "0.3.2"],
    { cwd: d, encoding: "utf8" });
  ck("sortie annonce les six emplacements", (r.match(/✓/g) || []).length >= 6);
  ck("cohérence relue après écriture", r.includes("cohérence relue"));
  const apres = lireVersions(d);
  ck("les six valent 0.3.2", apres.every((v) => v.version === "0.3.2"), JSON.stringify(apres.map((v) => v.version)));
  ck("voisins du Cargo.lock intacts",
    lireVersionDansLock(fs.readFileSync(path.join(d, "src-tauri/Cargo.lock"), "utf8"), "voisin-avant") === "9.9.9");
  fs.rmSync(d, { recursive: true, force: true });
}

console.log("\n-- bump : refus et blanc --");
{
  const d = sableNeuf("0.3.1");
  const essai = (args) => {
    try { return { code: 0, sortie: execFileSync("node", [path.join(RACINE, "bump_version.mjs"), ...args],
      { cwd: d, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }) }; }
    catch (e) { return { code: e.status, sortie: String(e.stdout ?? "") + String(e.stderr ?? "") }; }
  };
  const r1 = essai(["0.3.1"]);
  ck("version non postérieure refusée", r1.code !== 0 && r1.sortie.includes("n'est pas postérieure"), String(r1.code));
  ck("et rien n'a été écrit", lireVersions(d).every((v) => v.version === "0.3.1"));

  const r2 = essai(["0.3.0", "--force"]);
  ck("--force autorise le retour arrière", r2.code === 0 && lireVersions(d).every((v) => v.version === "0.3.0"), String(r2.code));

  const r3 = essai(["0.9.9", "--dry-run"]);
  ck("--dry-run n'écrit rien", r3.code === 0 && lireVersions(d).every((v) => v.version === "0.3.0"), String(r3.code));

  const r4 = essai(["0.9.9", "--tag"]);
  ck("--tag sans --git refusé", r4.code !== 0 && r4.sortie.includes("--tag exige --git"), String(r4.code));

  const r5 = essai(["--git", "--cargo", "1.0.0", "--dry-run"]);
  ck("drapeaux d'abord : la version est lue", r5.sortie.includes("version visée    : 1.0.0"), r5.sortie.slice(0, 80));
  fs.rmSync(d, { recursive: true, force: true });
}
{
  const d = sableNeuf("0.3.1");
  fs.rmSync(path.join(d, "src-tauri/Cargo.lock"));
  let code = 0;
  try { execFileSync("node", [path.join(RACINE, "bump_version.mjs"), "0.3.2"],
    { cwd: d, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }); }
  catch (e) { code = e.status; }
  ck("emplacement manquant : refus avant toute écriture", code !== 0);
  ck("et package.json n'a pas bougé",
    JSON.parse(fs.readFileSync(path.join(d, "package.json"), "utf8")).version === "0.3.1");
  fs.rmSync(d, { recursive: true, force: true });
}

console.log("\n-- réécrire la MÊME version reste licite --");
{
  // Défaut trouvé en exploitation : l'écriture dans Cargo.toml exigeait un changement de
  // texte, et levait donc quand la version était déjà la bonne — en laissant les quatre
  // premiers emplacements écrits. Réparer une dérive devenait impossible avec l'outil.
  const d = sableNeuf("0.3.1");
  const r = (() => {
    try { return { code: 0, sortie: execFileSync("node",
      [path.join(RACINE, "bump_version.mjs"), "0.3.1", "--force"],
      { cwd: d, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }) }; }
    catch (e) { return { code: e.status, sortie: String(e.stdout ?? "") + String(e.stderr ?? "") }; }
  })();
  ck("--force sur la version courante réussit", r.code === 0, r.sortie.split("\n").slice(-4).join(" | "));
  ck("les six restent à 0.3.1", lireVersions(d).every((v) => v.version === "0.3.1"));
  fs.rmSync(d, { recursive: true, force: true });
}
{
  // Cargo.toml sans ligne version : refus nommé, et pas d'exception nue.
  const d = sableNeuf("0.3.1");
  fs.writeFileSync(path.join(d, "src-tauri/Cargo.toml"), '[package]\nname = "human-origin"\n');
  let r = { code: 0, sortie: "" };
  try { r.sortie = execFileSync("node", [path.join(RACINE, "bump_version.mjs"), "0.3.2"],
    { cwd: d, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }); }
  catch (e) { r = { code: e.status, sortie: String(e.stdout ?? "") + String(e.stderr ?? "") }; }
  ck("ligne version absente : refus", r.code !== 0, String(r.code));
  ck("et le refus nomme l'emplacement et l'état incomplet",
    r.sortie.includes("Cargo.toml") && r.sortie.includes("INCOMPLÈTE"), r.sortie.trim().split("\n").pop());
  fs.rmSync(d, { recursive: true, force: true });
}

console.log(`\n  ${ok} réussis · ${ko} échoués  =>  OUTILLAGE_RELEASE = ${ko === 0 ? "PASS" : "FAIL"}\n`);
process.exit(ko === 0 ? 0 : 1);
